
services:


  unifi:
    user: unifi
    image: jacobalberty/unifi
    container_name: unifi-controller
    restart: unless-stopped
    network_mode: "host"
    environment:
      TZ: "Europe/Amsterdam"
    volumes:
      - ./data:/unifi

#-----------------------------------------

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #user: uid:gid
    networks:
      - Main_Network
    volumes:
      - /srv/docker/config/jellyfin/config:/config
      - /srv/docker/config/jellyfin/cache:/cache
      - type: bind
        source: /mnt/storage/docker/media/movies
        target: /movies
      - type: bind
        source: /mnt/storage/docker/media/series
        target: /series
        read_only: true
    restart: unless-stopped
    ports:
      - 8096:8096

#-----------------------------------------


  wordpress:
    image: wordpress
    ports:
      - 8089:80
    depends_on:
      - mysql_wordpress
    environment:
      WORDPRESS_DB_HOST: mysql_wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "coffee"
      WORDPRESS_DB_NAME: wordpress
    networks:
      - Wordpress_Network
#-----------------------------------------
  mysql_wordpress:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "coffee"
    networks:
      - Wordpress_Network
    volumes:
      - /srv/docker/config/wordpress/mysql:/var/lib/mysql
    restart: unless-stopped



#-----------------------------------------

  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - 8123:8123
    volumes:
      - /srv/docker/config/homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    networks:
     - Main_Network
    privileged: true

#-----------------------------------------

networks:
  Main_Network:
    ipam:
      driver: default
      config:
        - subnet: "10.0.1.0/24"
#-----------------------------------------
  Wordpress_Network:
    ipam:
      driver: default
      config:
        - subnet: "10.0.2.0/24"
#-----------------------------------------
  Cloudflare_Network:
    ipam:
      driver: default
      config:
        - subnet: "10.0.3.0/24"
#-----------------------------------------


